"""Nombre de país → código ISO-3166 alfa-2.

GENERADO POR herramientas/generar_paises.py — no editar a mano.
Para agregar un alias, tocá ALIAS en ese script y regeneralo.
"""

CODIGOS_POR_NOMBRE = {
    'afghanistan': 'AF',
    'ak': 'US',
    'al': 'US',
    'alabama': 'US',
    'alaska': 'US',
    'albania': 'AL',
    'algeria': 'DZ',
    'american samoa': 'AS',
    'andorra': 'AD',
    'angola': 'AO',
    'anguilla': 'AI',
    'antarctica': 'AQ',
    'antigua and barbuda': 'AG',
    'ar': 'US',
    'arab republic of egypt': 'EG',
    'argentina': 'AR',
    'argentine republic': 'AR',
    'arizona': 'US',
    'arkansas': 'US',
    'armenia': 'AM',
    'aruba': 'AW',
    'australia': 'AU',
    'austria': 'AT',
    'az': 'US',
    'azerbaijan': 'AZ',
    'bahamas': 'BS',
    'bahrain': 'BH',
    'bangladesh': 'BD',
    'barbados': 'BB',
    'belarus': 'BY',
    'belgium': 'BE',
    'belize': 'BZ',
    'benin': 'BJ',
    'bermuda': 'BM',
    'bhutan': 'BT',
    'bolivarian republic of venezuela': 'VE',
    'bolivia': 'BO',
    'bolivia, plurinational state of': 'BO',
    'bonaire': 'BQ',
    'bonaire, sint eustatius and saba': 'BQ',
    'bosnia and herzegovina': 'BA',
    'botswana': 'BW',
    'bouvet island': 'BV',
    'brazil': 'BR',
    'british indian ocean territory': 'IO',
    'british virgin islands': 'VG',
    'brunei': 'BN',
    'brunei darussalam': 'BN',
    'bulgaria': 'BG',
    'burkina faso': 'BF',
    'burma': 'MM',
    'burundi': 'BI',
    'ca': 'US',
    'cabo verde': 'CV',
    'california': 'US',
    'cambodia': 'KH',
    'cameroon': 'CM',
    'canada': 'CA',
    'cape verde': 'CV',
    'carolina': 'US',
    'cayman islands': 'KY',
    'central african republic': 'CF',
    'chad': 'TD',
    'chile': 'CL',
    'china': 'CN',
    'christmas island': 'CX',
    'co': 'US',
    'cocos (keeling) islands': 'CC',
    'colombia': 'CO',
    'colorado': 'US',
    'columbia': 'US',
    'commonwealth of dominica': 'DM',
    'commonwealth of the bahamas': 'BS',
    'commonwealth of the northern mariana islands': 'MP',
    'comoros': 'KM',
    'congo': 'CG',
    'congo, the democratic republic of the': 'CD',
    'connecticut': 'US',
    'cook islands': 'CK',
    'costa rica': 'CR',
    "cote d'ivoire": 'CI',
    'croatia': 'HR',
    'ct': 'US',
    'cuba': 'CU',
    'curaçao': 'CW',
    'cyprus': 'CY',
    'czech republic': 'CZ',
    'czechia': 'CZ',
    "côte d'ivoire": 'CI',
    'dakota': 'US',
    'dc': 'US',
    'de': 'US',
    'delaware': 'US',
    "democratic people's republic of korea": 'KP',
    'democratic republic of congo': 'CD',
    'democratic republic of sao tome and principe': 'ST',
    'democratic republic of timor-leste': 'TL',
    'democratic socialist republic of sri lanka': 'LK',
    'denmark': 'DK',
    'district': 'US',
    'district of columbia': 'US',
    'djibouti': 'DJ',
    'dominica': 'DM',
    'dominican republic': 'DO',
    'dr congo': 'CD',
    'east timor': 'TL',
    'eastern republic of uruguay': 'UY',
    'ecuador': 'EC',
    'egypt': 'EG',
    'el salvador': 'SV',
    'equatorial guinea': 'GQ',
    'eritrea': 'ER',
    'estonia': 'EE',
    'eswatini': 'SZ',
    'ethiopia': 'ET',
    'falkland islands (malvinas)': 'FK',
    'faroe islands': 'FO',
    'federal democratic republic of ethiopia': 'ET',
    'federal democratic republic of nepal': 'NP',
    'federal republic of germany': 'DE',
    'federal republic of nigeria': 'NG',
    'federal republic of somalia': 'SO',
    'federated states of micronesia': 'FM',
    'federative republic of brazil': 'BR',
    'fiji': 'FJ',
    'finland': 'FI',
    'fl': 'US',
    'florida': 'US',
    'france': 'FR',
    'french guiana': 'GF',
    'french polynesia': 'PF',
    'french republic': 'FR',
    'french southern territories': 'TF',
    'ga': 'US',
    'gabon': 'GA',
    'gabonese republic': 'GA',
    'gambia': 'GM',
    'georgia': 'US',
    'germany': 'DE',
    'ghana': 'GH',
    'gibraltar': 'GI',
    'grand duchy of luxembourg': 'LU',
    'greece': 'GR',
    'greenland': 'GL',
    'grenada': 'GD',
    'guadeloupe': 'GP',
    'guam': 'GU',
    'guatemala': 'GT',
    'guernsey': 'GG',
    'guinea': 'GN',
    'guinea-bissau': 'GW',
    'guyana': 'GY',
    'haiti': 'HT',
    'hampshire': 'US',
    'hashemite kingdom of jordan': 'JO',
    'hawaii': 'US',
    'heard island and mcdonald islands': 'HM',
    'hellenic republic': 'GR',
    'hi': 'US',
    'holy see (vatican city state)': 'VA',
    'honduras': 'HN',
    'hong kong': 'HK',
    'hong kong special administrative region of china': 'HK',
    'hungary': 'HU',
    'ia': 'US',
    'iceland': 'IS',
    'id': 'US',
    'idaho': 'US',
    'il': 'US',
    'illinois': 'US',
    'in': 'US',
    'independent state of papua new guinea': 'PG',
    'independent state of samoa': 'WS',
    'india': 'IN',
    'indiana': 'US',
    'indonesia': 'ID',
    'iowa': 'US',
    'iran': 'IR',
    'iran, islamic republic of': 'IR',
    'iraq': 'IQ',
    'ireland': 'IE',
    'islamic republic of afghanistan': 'AF',
    'islamic republic of iran': 'IR',
    'islamic republic of mauritania': 'MR',
    'islamic republic of pakistan': 'PK',
    'island': 'US',
    'isle of man': 'IM',
    'israel': 'IL',
    'italian republic': 'IT',
    'italy': 'IT',
    'ivory coast': 'CI',
    'jamaica': 'JM',
    'japan': 'JP',
    'jersey': 'US',
    'jordan': 'JO',
    'kansas': 'US',
    'kazakhstan': 'KZ',
    'kentucky': 'US',
    'kenya': 'KE',
    'kingdom of bahrain': 'BH',
    'kingdom of belgium': 'BE',
    'kingdom of bhutan': 'BT',
    'kingdom of cambodia': 'KH',
    'kingdom of denmark': 'DK',
    'kingdom of eswatini': 'SZ',
    'kingdom of lesotho': 'LS',
    'kingdom of morocco': 'MA',
    'kingdom of norway': 'NO',
    'kingdom of saudi arabia': 'SA',
    'kingdom of spain': 'ES',
    'kingdom of sweden': 'SE',
    'kingdom of thailand': 'TH',
    'kingdom of the netherlands': 'NL',
    'kingdom of tonga': 'TO',
    'kiribati': 'KI',
    'korea': 'KR',
    "korea, democratic people's republic of": 'KP',
    'korea, republic of': 'KR',
    'ks': 'US',
    'kuwait': 'KW',
    'ky': 'US',
    'kyrgyz republic': 'KG',
    'kyrgyzstan': 'KG',
    'la': 'US',
    "lao people's democratic republic": 'LA',
    'laos': 'LA',
    'latvia': 'LV',
    'lebanese republic': 'LB',
    'lebanon': 'LB',
    'lesotho': 'LS',
    'liberia': 'LR',
    'libya': 'LY',
    'liechtenstein': 'LI',
    'lithuania': 'LT',
    'louisiana': 'US',
    'luxembourg': 'LU',
    'ma': 'US',
    'macao': 'MO',
    'macao special administrative region of china': 'MO',
    'macedonia': 'MK',
    'madagascar': 'MG',
    'maine': 'US',
    'malawi': 'MW',
    'malaysia': 'MY',
    'maldives': 'MV',
    'mali': 'ML',
    'malta': 'MT',
    'marshall islands': 'MH',
    'martinique': 'MQ',
    'maryland': 'US',
    'massachusetts': 'US',
    'mauritania': 'MR',
    'mauritius': 'MU',
    'mayotte': 'YT',
    'md': 'US',
    'me': 'US',
    'mexico': 'US',
    'mi': 'US',
    'michigan': 'US',
    'micronesia': 'FM',
    'micronesia, federated states of': 'FM',
    'minnesota': 'US',
    'mississippi': 'US',
    'missouri': 'US',
    'mn': 'US',
    'mo': 'US',
    'moldova': 'MD',
    'moldova, republic of': 'MD',
    'monaco': 'MC',
    'mongolia': 'MN',
    'montana': 'US',
    'montenegro': 'ME',
    'montserrat': 'MS',
    'morocco': 'MA',
    'mozambique': 'MZ',
    'ms': 'US',
    'mt': 'US',
    'myanmar': 'MM',
    'namibia': 'NA',
    'nauru': 'NR',
    'nc': 'US',
    'nd': 'US',
    'ne': 'US',
    'nebraska': 'US',
    'nepal': 'NP',
    'netherlands': 'NL',
    'nevada': 'US',
    'new': 'US',
    'new caledonia': 'NC',
    'new hampshire': 'US',
    'new jersey': 'US',
    'new mexico': 'US',
    'new york': 'US',
    'new zealand': 'NZ',
    'nh': 'US',
    'nicaragua': 'NI',
    'niger': 'NE',
    'nigeria': 'NG',
    'niue': 'NU',
    'nj': 'US',
    'nm': 'US',
    'norfolk island': 'NF',
    'north': 'US',
    'north carolina': 'US',
    'north dakota': 'US',
    'north korea': 'KP',
    'north macedonia': 'MK',
    'northern mariana islands': 'MP',
    'norway': 'NO',
    'nv': 'US',
    'ny': 'US',
    'of': 'US',
    'oh': 'US',
    'ohio': 'US',
    'ok': 'US',
    'oklahoma': 'US',
    'oman': 'OM',
    'or': 'US',
    'oregon': 'US',
    'pa': 'US',
    'pakistan': 'PK',
    'palau': 'PW',
    'palestine': 'PS',
    'palestine, state of': 'PS',
    'panama': 'PA',
    'papua new guinea': 'PG',
    'paraguay': 'PY',
    'pennsylvania': 'US',
    "people's democratic republic of algeria": 'DZ',
    "people's republic of bangladesh": 'BD',
    "people's republic of china": 'CN',
    'peru': 'PE',
    'philippines': 'PH',
    'pitcairn': 'PN',
    'plurinational state of bolivia': 'BO',
    'poland': 'PL',
    'portugal': 'PT',
    'portuguese republic': 'PT',
    'principality of andorra': 'AD',
    'principality of liechtenstein': 'LI',
    'principality of monaco': 'MC',
    'puerto rico': 'PR',
    'qatar': 'QA',
    'republic of albania': 'AL',
    'republic of angola': 'AO',
    'republic of armenia': 'AM',
    'republic of austria': 'AT',
    'republic of azerbaijan': 'AZ',
    'republic of belarus': 'BY',
    'republic of benin': 'BJ',
    'republic of bosnia and herzegovina': 'BA',
    'republic of botswana': 'BW',
    'republic of bulgaria': 'BG',
    'republic of burundi': 'BI',
    'republic of cabo verde': 'CV',
    'republic of cameroon': 'CM',
    'republic of chad': 'TD',
    'republic of chile': 'CL',
    'republic of colombia': 'CO',
    'republic of congo': 'CG',
    'republic of costa rica': 'CR',
    'republic of croatia': 'HR',
    'republic of cuba': 'CU',
    'republic of cyprus': 'CY',
    "republic of côte d'ivoire": 'CI',
    'republic of djibouti': 'DJ',
    'republic of ecuador': 'EC',
    'republic of el salvador': 'SV',
    'republic of equatorial guinea': 'GQ',
    'republic of estonia': 'EE',
    'republic of fiji': 'FJ',
    'republic of finland': 'FI',
    'republic of ghana': 'GH',
    'republic of guatemala': 'GT',
    'republic of guinea': 'GN',
    'republic of guinea-bissau': 'GW',
    'republic of guyana': 'GY',
    'republic of haiti': 'HT',
    'republic of honduras': 'HN',
    'republic of iceland': 'IS',
    'republic of india': 'IN',
    'republic of indonesia': 'ID',
    'republic of iraq': 'IQ',
    'republic of kazakhstan': 'KZ',
    'republic of kenya': 'KE',
    'republic of kiribati': 'KI',
    'republic of latvia': 'LV',
    'republic of liberia': 'LR',
    'republic of lithuania': 'LT',
    'republic of madagascar': 'MG',
    'republic of malawi': 'MW',
    'republic of maldives': 'MV',
    'republic of mali': 'ML',
    'republic of malta': 'MT',
    'republic of mauritius': 'MU',
    'republic of moldova': 'MD',
    'republic of mozambique': 'MZ',
    'republic of myanmar': 'MM',
    'republic of namibia': 'NA',
    'republic of nauru': 'NR',
    'republic of nicaragua': 'NI',
    'republic of north macedonia': 'MK',
    'republic of palau': 'PW',
    'republic of panama': 'PA',
    'republic of paraguay': 'PY',
    'republic of peru': 'PE',
    'republic of poland': 'PL',
    'republic of san marino': 'SM',
    'republic of senegal': 'SN',
    'republic of serbia': 'RS',
    'republic of seychelles': 'SC',
    'republic of sierra leone': 'SL',
    'republic of singapore': 'SG',
    'republic of slovenia': 'SI',
    'republic of south africa': 'ZA',
    'republic of south sudan': 'SS',
    'republic of suriname': 'SR',
    'republic of tajikistan': 'TJ',
    'republic of the congo': 'CG',
    'republic of the gambia': 'GM',
    'republic of the marshall islands': 'MH',
    'republic of the niger': 'NE',
    'republic of the philippines': 'PH',
    'republic of the sudan': 'SD',
    'republic of trinidad and tobago': 'TT',
    'republic of tunisia': 'TN',
    'republic of türkiye': 'TR',
    'republic of uganda': 'UG',
    'republic of uzbekistan': 'UZ',
    'republic of vanuatu': 'VU',
    'republic of yemen': 'YE',
    'republic of zambia': 'ZM',
    'republic of zimbabwe': 'ZW',
    'rhode': 'US',
    'rhode island': 'US',
    'ri': 'US',
    'romania': 'RO',
    'russia': 'RU',
    'russian federation': 'RU',
    'rwanda': 'RW',
    'rwandese republic': 'RW',
    'réunion': 'RE',
    'saint barthélemy': 'BL',
    'saint helena': 'SH',
    'saint helena, ascension and tristan da cunha': 'SH',
    'saint kitts and nevis': 'KN',
    'saint lucia': 'LC',
    'saint martin (french part)': 'MF',
    'saint pierre and miquelon': 'PM',
    'saint vincent and the grenadines': 'VC',
    'samoa': 'WS',
    'san marino': 'SM',
    'sao tome and principe': 'ST',
    'saudi arabia': 'SA',
    'sc': 'US',
    'sd': 'US',
    'senegal': 'SN',
    'serbia': 'RS',
    'seychelles': 'SC',
    'sierra leone': 'SL',
    'singapore': 'SG',
    'sint maarten (dutch part)': 'SX',
    'slovak republic': 'SK',
    'slovakia': 'SK',
    'slovenia': 'SI',
    'socialist republic of viet nam': 'VN',
    'solomon islands': 'SB',
    'somalia': 'SO',
    'south': 'US',
    'south africa': 'ZA',
    'south carolina': 'US',
    'south dakota': 'US',
    'south georgia and the south sandwich islands': 'GS',
    'south korea': 'KR',
    'south sudan': 'SS',
    'spain': 'ES',
    'sri lanka': 'LK',
    'state of israel': 'IL',
    'state of kuwait': 'KW',
    'state of qatar': 'QA',
    'sudan': 'SD',
    'sultanate of oman': 'OM',
    'suriname': 'SR',
    'svalbard and jan mayen': 'SJ',
    'swaziland': 'SZ',
    'sweden': 'SE',
    'swiss confederation': 'CH',
    'switzerland': 'CH',
    'syria': 'SY',
    'syrian arab republic': 'SY',
    'taiwan': 'TW',
    'taiwan, province of china': 'TW',
    'tajikistan': 'TJ',
    'tanzania': 'TZ',
    'tanzania, united republic of': 'TZ',
    'tennessee': 'US',
    'texas': 'US',
    'thailand': 'TH',
    'the bahamas': 'BS',
    'the democratic republic of congo': 'CD',
    'the gambia': 'GM',
    'the netherlands': 'NL',
    'the philippines': 'PH',
    'the state of eritrea': 'ER',
    'the state of palestine': 'PS',
    'timor-leste': 'TL',
    'tn': 'US',
    'togo': 'TG',
    'togolese republic': 'TG',
    'tokelau': 'TK',
    'tonga': 'TO',
    'trinidad and tobago': 'TT',
    'tunisia': 'TN',
    'turkey': 'TR',
    'turkmenistan': 'TM',
    'turks and caicos islands': 'TC',
    'tuvalu': 'TV',
    'tx': 'US',
    'türkiye': 'TR',
    'u.s. virgin islands': 'VI',
    'u.s.a.': 'US',
    'uganda': 'UG',
    'uk': 'GB',
    'ukraine': 'UA',
    'union of the comoros': 'KM',
    'united arab emirates': 'AE',
    'united kingdom': 'GB',
    'united kingdom of great britain and northern ireland': 'GB',
    'united mexican states': 'MX',
    'united republic of tanzania': 'TZ',
    'united states': 'US',
    'united states minor outlying islands': 'UM',
    'united states of america': 'US',
    'uruguay': 'UY',
    'us virgin islands': 'VI',
    'usa': 'US',
    'ut': 'US',
    'utah': 'US',
    'uzbekistan': 'UZ',
    'va': 'US',
    'vanuatu': 'VU',
    'vatican city': 'VA',
    'venezuela': 'VE',
    'venezuela, bolivarian republic of': 'VE',
    'vermont': 'US',
    'viet nam': 'VN',
    'vietnam': 'VN',
    'virgin islands': 'VG',
    'virgin islands of the united states': 'VI',
    'virgin islands, british': 'VG',
    'virgin islands, u.s.': 'VI',
    'virginia': 'US',
    'vt': 'US',
    'wa': 'US',
    'wallis and futuna': 'WF',
    'washington': 'US',
    'west': 'US',
    'west virginia': 'US',
    'western sahara': 'EH',
    'wi': 'US',
    'wisconsin': 'US',
    'wv': 'US',
    'wy': 'US',
    'wyoming': 'US',
    'yemen': 'YE',
    'york': 'US',
    'zambia': 'ZM',
    'zimbabwe': 'ZW',
    'åland islands': 'AX',
}

# Alfa-2 válidos, para aceptar códigos que una fuente ya publica así.
CODIGOS_VALIDOS = frozenset({
    'AD',
    'AE',
    'AF',
    'AG',
    'AI',
    'AL',
    'AM',
    'AO',
    'AQ',
    'AR',
    'AS',
    'AT',
    'AU',
    'AW',
    'AX',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BL',
    'BM',
    'BN',
    'BO',
    'BQ',
    'BR',
    'BS',
    'BT',
    'BV',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CC',
    'CD',
    'CF',
    'CG',
    'CH',
    'CI',
    'CK',
    'CL',
    'CM',
    'CN',
    'CO',
    'CR',
    'CU',
    'CV',
    'CW',
    'CX',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'EH',
    'ER',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FK',
    'FM',
    'FO',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GF',
    'GG',
    'GH',
    'GI',
    'GL',
    'GM',
    'GN',
    'GP',
    'GQ',
    'GR',
    'GS',
    'GT',
    'GU',
    'GW',
    'GY',
    'HK',
    'HM',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IM',
    'IN',
    'IO',
    'IQ',
    'IR',
    'IS',
    'IT',
    'JE',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KP',
    'KR',
    'KW',
    'KY',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MF',
    'MG',
    'MH',
    'MK',
    'ML',
    'MM',
    'MN',
    'MO',
    'MP',
    'MQ',
    'MR',
    'MS',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NC',
    'NE',
    'NF',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NU',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PF',
    'PG',
    'PH',
    'PK',
    'PL',
    'PM',
    'PN',
    'PR',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RE',
    'RO',
    'RS',
    'RU',
    'RW',
    'SA',
    'SB',
    'SC',
    'SD',
    'SE',
    'SG',
    'SH',
    'SI',
    'SJ',
    'SK',
    'SL',
    'SM',
    'SN',
    'SO',
    'SR',
    'SS',
    'ST',
    'SV',
    'SX',
    'SY',
    'SZ',
    'TC',
    'TD',
    'TF',
    'TG',
    'TH',
    'TJ',
    'TK',
    'TL',
    'TM',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'UM',
    'US',
    'UY',
    'UZ',
    'VA',
    'VC',
    'VE',
    'VG',
    'VI',
    'VN',
    'VU',
    'WF',
    'WS',
    'YE',
    'YT',
    'ZA',
    'ZM',
    'ZW',
})
